# Generated by Django 3.1 on 2021-02-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=13, unique=True, verbose_name='Codigo del cupon'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Total'),
        ),
    ]
