# Generated by Django 3.1 on 2021-02-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comment',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Comentario de la receta'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Descripcion de la receta'),
        ),
    ]
