# Generated by Django 3.1 on 2021-03-02 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shipping_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shippinginfo'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipelabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.label'),
        ),
        migrations.AddField(
            model_name='recipelabel',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.recipe'),
        ),
        migrations.AddField(
            model_name='recipedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.product'),
        ),
        migrations.AddField(
            model_name='recipedetail',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.recipe'),
        ),
        migrations.AddField(
            model_name='recipecomment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.recipe'),
        ),
        migrations.AddField(
            model_name='recipecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='comment',
            field=models.ManyToManyField(through='foods.RecipeComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='detail',
            field=models.ManyToManyField(through='foods.RecipeDetail', to='foods.Product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='label',
            field=models.ManyToManyField(through='foods.RecipeLabel', to='foods.Label'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.recipecategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.productcategory'),
        ),
        migrations.AddField(
            model_name='planningdetail',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.planning'),
        ),
        migrations.AddField(
            model_name='planningdetail',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.recipe'),
        ),
        migrations.AddField(
            model_name='planning',
            name='detail',
            field=models.ManyToManyField(through='foods.PlanningDetail', to='foods.Recipe'),
        ),
        migrations.AddField(
            model_name='planning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
