# Generated by Django 3.1 on 2021-02-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20210228_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Codigo de seguimiento'),
        ),
    ]
