# Generated by Django 3.1 on 2021-02-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20210227_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='total_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=19, verbose_name='Tiempo que se demora en preparar la receta'),
        ),
    ]
