# Generated by Django 3.1 on 2021-03-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20210302_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoria'),
        ),
    ]
