# Generated by Django 3.1 on 2021-02-27 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0002_auto_20210227_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Time de la creacion del objeto', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date Time de la ultima modificacion del objeto', verbose_name='modified at')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='La fila esta activa o no', verbose_name='is active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoria')),
                ('date', models.CharField(blank=True, choices=[('S', 'Semanal'), ('M', 'Mensual')], default='S', max_length=1, verbose_name='Tipo de planificacion')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripcion de la planificacion')),
            ],
            options={
                'ordering': ['-created', 'modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sale',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Comentario de la venta'),
        ),
        migrations.CreateModel(
            name='PlanningDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Time de la creacion del objeto', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date Time de la ultima modificacion del objeto', verbose_name='modified at')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='La fila esta activa o no', verbose_name='is active')),
                ('day', models.DateTimeField(verbose_name='Dia de la semana o del mes')),
                ('time', models.CharField(choices=[('D', 'Desayuno'), ('A', 'Almuerzo'), ('M', 'Merienda'), ('C', 'Cena')], max_length=1, verbose_name='Tipo de planificacion')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.planning')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.recipe')),
            ],
            options={
                'ordering': ['-created', 'modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planning',
            name='detail',
            field=models.ManyToManyField(through='foods.PlanningDetail', to='foods.Recipe'),
        ),
        migrations.AddField(
            model_name='planning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
