# Generated by Django 3.1 on 2021-02-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20210227_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Descuento del cupon'),
        ),
        migrations.AlterField(
            model_name='recipedetail',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Sub total'),
        ),
    ]
