# Generated by Django 3.1 on 2021-03-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20210302_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='foods/pictures/', verbose_name='Imagen de la receta'),
        ),
    ]
