# Generated by Django 3.1 on 2021-02-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20210227_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la planificacion'),
        ),
    ]
