# Generated by Django 3.1 on 2021-02-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20210228_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='finalize',
            field=models.BooleanField(blank=True, default=False, verbose_name='Estado de finalizacion de la venta'),
        ),
    ]
