# Generated by Django 3.1 on 2021-03-02 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('foods', '0003_auto_20210302_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='shipping_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.shippinginfo'),
        ),
    ]
