# Generated by Django 3.1 on 2021-03-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20210305_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19, verbose_name='Cantidad del producto'),
        ),
        migrations.AlterField(
            model_name='recipedetail',
            name='unit',
            field=models.CharField(default='100g', max_length=50, verbose_name='Cantidad real del producto'),
            preserve_default=False,
        ),
    ]
