# Generated by Django 3.1 on 2021-03-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20210302_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del cupon'),
        ),
        migrations.AlterField(
            model_name='planningdetail',
            name='time',
            field=models.CharField(choices=[('A', 'Almuerzo'), ('C', 'Cena'), ('P', 'Postre')], max_length=1, verbose_name='Tipo de planificacion'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('D', 'Debito'), ('T', 'Credito'), ('T', 'Paypal')], default='C', max_length=1, verbose_name='Tipo de metodo de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='steps',
            field=models.CharField(blank=True, choices=[('R', 'Pedido recibido'), ('C', 'Realizando las compras'), ('P', 'Preparando el pedido'), ('CA', 'Pedido en camino'), ('E', 'Pedido entregado')], default='P', max_length=2, verbose_name='Seguimiento de la venta'),
        ),
    ]
