# Generated by Django 3.1 on 2021-03-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20210305_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecategory',
            name='icon_svg',
        ),
        migrations.AddField(
            model_name='recipecategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='foods/pictures/', verbose_name='Imagen de la categoria'),
        ),
    ]
