# Generated by Django 3.1 on 2021-03-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20210303_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipelabel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='recipelabel',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='label',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tips',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='utensils',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='icon_svg',
            field=models.TextField(default='adasda', max_length=500, verbose_name='Codigo del icono'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='RecipeLabel',
        ),
    ]
