# Generated by Django 3.1 on 2021-03-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20210306_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=19, verbose_name='Inventario del producto'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Cantidad del producto'),
        ),
    ]
