# Generated by Django 3.1 on 2021-02-25 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El numero de celular tiene que tener el formato: +999999999. Hasta 15 digitos', regex='\\+?1?\\d{9,15}$')]),
        ),
    ]
