# Generated by Django 3.1 on 2021-02-26 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Time de la creacion del objeto', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date Time de la ultima modificacion del objeto', verbose_name='modified at')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='La fila esta activa o no', verbose_name='is active')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre del perfil')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido del perfil')),
                ('country', models.CharField(max_length=30, verbose_name='Pais donde vive')),
                ('street_address', models.CharField(max_length=30, verbose_name='Direccion de la calle')),
                ('apartament', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apartamente donde vive')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad donde vive')),
                ('state', models.CharField(max_length=30, verbose_name='Estado/provincia donde vive')),
                ('zip_code', models.IntegerField(verbose_name='Codigo postal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', 'modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
